# Dependencies
#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bay Area UrbanSim
tagline:          'Metropolitan Transportation Commission'
url:              http://metropolitantransportationcommission.github.io/bayarea_urbansim
shorturl:         metropolitantransportationcommission.github.io/bayarea_urbansim

author:
  name:           'Michael Reilly'
  url:            https://github.com/mkreilly

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/metropolitantransportationcommission/bayarea_urbansim/tree/gh-pages

# This is the list of pages to include in the header of the website.
pages_list:       
  Model Overview: 'model_overview/'
  Input Data Preparation: 'input_data/'
  Users Guide: 'users_guide/'
  Plan Bay Area 2050: 'pba2050/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
